site_name: Rakesh
# repo_url: https://github.com/rakeshcusat/rakeshcusat.github.io
copyright: Copyright &copy; 2019 - 2025 Rakesh Kumar â€“
  <a href="#__consent">Change cookie settings</a>
site_url: https://www.englife101.io/
use_directory_urls: false
theme:
  name: 'material'
  features:
    - navigation.footer
nav:
  - Home: index.md
  - Experience: experience.md
  - Projects: projects.md
  - Public Speaking: public-speaking.md

# Additional configuration
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rakeshcusat
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/englife101
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/englife101
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rakeshkumar1007/
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our website and whether users
      find what they're searching for. With your consent, you're helping us to
      make our website better.
    cookies:
      analytics:
          name: Google Analytics
          checked: true
      github:
          name: github
          checked: true

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - pymdownx.critic
  - pymdownx.details
  - toc:
      toc_depth: 4
      permalink: ðŸ”—

plugins:
  - awesome-pages
  - htmlproofer:
      enabled: True
      validate_external_urls: True
      raise_error: True
  - search
  - social
  - privacy